apiVersion : apps/v1
kind: Deployment
metadata:
  name: nodejstest123
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejstest123
  template:
    metadata:
      labels:
        app: nodejstest123 
    spec:
      containers:
        - name: nodejstest123 
          image: kcscr.azurecr.io/nodejstest123
          ports:
          - containerPort: 3000
